name: maignanka_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences:
  intl: ^0.20.2
  timeago: ^3.7.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  pinput: ^5.0.1
  mime_type: ^1.0.1
  socket_io_client: ^3.1.2
  logger: ^2.5.0
  lottie: ^3.3.1
  flutter_svg:
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_widget_from_html: ^0.16.0
  dots_indicator: ^4.0.1
  chat_bubbles: ^1.7.0
  bottom_picker:
  dotted_border: ^2.0.0
  permission_handler: ^11.0.1
  geolocator: ^11.0.0
  badges:
  grouped_list: ^6.0.0
  flutter_card_swiper:
  like_button: ^2.1.0
  flutter_advanced_drawer:
  photo_view:
  heart_overlay: ^1.4.1
  avatar_glow: ^3.0.1
  flutter_inappwebview: ^6.1.5
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.10
  flutter_staggered_grid_view: ^0.7.0
  connectivity_plus: ^6.1.4
  custom_image_crop: ^0.1.1
  flutter_image_compress: ^2.4.0
  image: ^4.2.0
  flutter_local_notifications:
  pay: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.14.4




flutter_gen:
  output: lib/global/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    lottie: true
    #===========>>>>>>>>>> Flutter Gen Code ==============>>>>>>>>>>>
    # dart pub global activate flutter_gen
    # flutter pub run build_runner build --delete-conflicting-outputs
    # flutter pub run build_runner build

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"


#  fvm flutter pub get
#  fvm flutter pub run flutter_launcher_icons



flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
